[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@node-rs/bcrypt"]

[dev]
framework = "#custom"
command = "npm run dev"
port = 5001
targetPort = 5001

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true